services:
  - type: web
    name: final-project
    runtime: node
    plan: free
    buildCommand: cd final-project-template && npm install && npx prisma migrate deploy && npx prisma generate && npm run seed:prod
    startCommand: cd final-project-template && npm run start
    envVars:
      - key: DATABASE_URL
